# Generated by Django 4.1.1 on 2022-10-31 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(blank=True, default='', max_length=250, unique=True, verbose_name='Name')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('exp_interval', models.IntegerField(blank=True, default=0, null=True, verbose_name='Expiration interval in days')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(blank=True, default='', max_length=250, null=True, unique=True, verbose_name='Role')),
                ('certificates_list', models.ManyToManyField(blank=True, to='users.certificate')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('roles_list', models.ManyToManyField(blank=True, to='users.role')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=users.models.getPathToSave)),
                ('certification_completion_date', models.DateTimeField(default=None, null=True, verbose_name='Completion date')),
                ('certification_due_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Due date')),
                ('certificate', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.certificate')),
                ('profile', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
