# Generated by Django 4.1.1 on 2022-10-31 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='Valid'),
        ),
    ]
