# Generated by Django 4.1.1 on 2022-10-13 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_image_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
