# Generated by Django 4.1.1 on 2022-11-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
