# Generated by Django 4.1.1 on 2022-10-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='image_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Наименование услуги'),
        ),
    ]
