# Generated by Django 4.1.1 on 2022-10-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_image_images_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Certificate name'),
        ),
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.FileField(upload_to='certificates/%Y/%m/%d/'),
        ),
    ]
