# Generated by Django 4.1.1 on 2022-11-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_certificate_limited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='limited',
        ),
        migrations.AddField(
            model_name='certificate',
            name='is_limited',
            field=models.BooleanField(default=True, verbose_name='Time Limited'),
        ),
    ]
