# Generated by Django 4.1.1 on 2022-10-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_images_image_name_alter_images_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/%d/'),
        ),
    ]
