# Generated by Django 4.1.1 on 2022-10-13 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_alter_images_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Certificate name'),
        ),
        migrations.AlterField(
            model_name='images',
            name='profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='roles_list',
            field=models.ManyToManyField(blank=True, null=True, to='users.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='certificates_list',
            field=models.ManyToManyField(blank=True, null=True, to='users.certificate'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Role'),
        ),
    ]
