# Generated by Django 4.1.1 on 2022-10-13 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_images_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='certificate',
        ),
    ]
