# Generated by Django 4.1.1 on 2022-10-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_images_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='certificates_list',
            field=models.ManyToManyField(blank=True, to='users.certificate'),
        ),
    ]
