# Generated by Django 4.1.1 on 2022-10-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_role_certificates_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roles_list',
            field=models.ManyToManyField(blank=True, to='users.role'),
        ),
    ]
