# Generated by Django 4.1.1 on 2022-10-14 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_images_certificate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
    ]
