# Generated by Django 4.1.1 on 2022-10-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_images_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_name',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Certificate name'),
        ),
    ]
