# Generated by Django 4.1.1 on 2022-10-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_images_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.FileField(null=True, upload_to='certificates/%Y/%m/%d/'),
        ),
    ]
