# Generated by Django 4.1.1 on 2022-10-15 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_images_certificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='images',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='images',
            name='certificate',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.certificate'),
        ),
    ]
