# Generated by Django 4.1.1 on 2022-10-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_rename_images_images_file_alter_images_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image_name',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_name',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Role'),
        ),
    ]
