# Generated by Django 4.1.1 on 2022-10-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_images_image_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
    ]
