# Generated by Django 4.1.1 on 2022-10-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='uploaded_on',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Uploaded on'),
        ),
    ]
