# Generated by Django 4.1.1 on 2022-10-19 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_images_uploaded_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='exp_interval',
            field=models.IntegerField(blank=True, null=True, verbose_name='Expiration interval in days'),
        ),
        migrations.AlterField(
            model_name='images',
            name='uploaded_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 19, 21, 36, 53, 917158, tzinfo=datetime.timezone.utc), null=True, verbose_name='Uploaded on'),
        ),
    ]
