# Generated by Django 4.1.1 on 2022-10-20 01:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_certificate_exp_interval_alter_images_uploaded_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dicty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_name',
            field=models.CharField(blank=True, default='', max_length=250, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='images',
            name='uploaded_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 20, 1, 2, 5, 694690, tzinfo=datetime.timezone.utc), null=True, verbose_name='Uploaded on'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(blank=True, default='', max_length=250, null=True, unique=True, verbose_name='Role'),
        ),
        migrations.CreateModel(
            name='KeyVal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=200)),
                ('value', models.IntegerField(db_index=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dicty')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='cert_due_date_list',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.dicty'),
        ),
    ]
