# Generated by Django 4.1.1 on 2022-10-20 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_dicty_alter_certificate_certificate_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyval',
            name='container',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cert_due_date_list',
        ),
        migrations.AlterField(
            model_name='images',
            name='uploaded_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 20, 1, 12, 2, 353586, tzinfo=datetime.timezone.utc), null=True, verbose_name='Uploaded on'),
        ),
        migrations.DeleteModel(
            name='Dicty',
        ),
        migrations.DeleteModel(
            name='KeyVal',
        ),
    ]
