# Generated by Django 4.1.1 on 2022-10-20 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_remove_keyval_container_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='uploaded_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 20, 1, 25, 39, 769268, tzinfo=datetime.timezone.utc), null=True, verbose_name='Uploaded on'),
        ),
    ]
