# Generated by Django 4.1.1 on 2022-10-23 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_images_uploaded_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='uploaded_on',
        ),
        migrations.AddField(
            model_name='images',
            name='certification_completion_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='Uploaded on'),
        ),
        migrations.AlterField(
            model_name='images',
            name='certificate',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.certificate'),
        ),
    ]
