# Generated by Django 4.1.1 on 2022-10-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_images_certification_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='certification_completion_date',
            field=models.DateField(default=None, null=True, verbose_name='Completion date'),
        ),
    ]
